name: Compile Assets

on:
  push:
    paths: ['resources/**']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5

    - uses: actions/setup-node@v6
      with:
        node-version: 24

    - name: Install NPM dependencies
      run: npm ci

    - name: Compile assets
      run: npm run build

    - name: Commit compiled files
      uses: stefanzweifel/git-auto-commit-action@v7
      with:
        commit_message: "chore: build"
        file_pattern: public/
